baseURL = 'https://engmaths.github.io/ddes-dte/'
languageCode = 'en-gb'
title = 'Data-Driven Engineering and Sciences PhD Programme'
theme = 'beautifulhugo'

[Params]
homeTitle = "Data-Driven Engineering and Sciences"                                     # Set a different text for the header on the home page
subtitle = "A cohort-based doctoral training environment at the University of Bristol"
mainSections = ["post", "posts"]
logo = "img/uob-square.svg"                                                            # Expecting square dimensions
dateFormat = "2 January 2006"
